import { Cookie, Poiret_One, Ubuntu, Ubuntu_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


const poiret = Poiret_One({
  weight: "400",
  variable: "--font-poiret",
  subsets: ["latin"],
});

const cookie = Cookie({
  weight: "400",
  variable: "--font-cookie",
  subsets: ["latin"],
});

const ubuntu = Ubuntu({
  weight: "400",
  variable: "--font-ubuntu",
  subsets: ["latin"],
});

const ubuntuCondensed = Ubuntu_Condensed({
  weight: "400",
  variable: "--font-ubuntu-condensed",
  subsets: ["latin"],
});

export const metadata = {
  title: "D-RADAR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poiret.variable} ${cookie} ${ubuntu} ${ubuntuCondensed} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
